package lk.zaa.sunrise.api.entity;

import jakarta.persistence.*;
import lk.zaa.sunrise.common.enums.AppointmentStatus;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * The central entity of the system. appointmentNumber is generated by
 * AppointmentNumberGenerator (Singleton pattern) rather than typed in by staff,
 * which is what stops the double-booking / duplicate-ID problem named in the
 * clinic scenario (Task A Assumption 5). A DB-level trigger (see schema.sql)
 * provides a second line of defence against a dentist being double-booked for
 * the same date and time.
 */
@Entity
@Table(name = "appointments", uniqueConstraints = {
        @UniqueConstraint(name = "uk_appointment_number", columnNames = "appointment_number")
})
public class Appointment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "appointment_number", nullable = false, unique = true, length = 20)
    private String appointmentNumber;

    @ManyToOne(optional = false)
    @JoinColumn(name = "patient_id")
    private Patient patient;

    @ManyToOne(optional = false)
    @JoinColumn(name = "dentist_id")
    private Dentist dentist;

    @ManyToOne(optional = false)
    @JoinColumn(name = "treatment_id")
    private TreatmentType treatmentType;

    @Column(nullable = false)
    private LocalDate appointmentDate;

    @Column(nullable = false)
    private LocalTime appointmentTime;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private AppointmentStatus status = AppointmentStatus.SCHEDULED;

    protected Appointment() {
    }

    public Appointment(String appointmentNumber, Patient patient, Dentist dentist,
                        TreatmentType treatmentType, LocalDate appointmentDate, LocalTime appointmentTime) {
        this.appointmentNumber = appointmentNumber;
        this.patient = patient;
        this.dentist = dentist;
        this.treatmentType = treatmentType;
        this.appointmentDate = appointmentDate;
        this.appointmentTime = appointmentTime;
    }

    public Long getId() { return id; }
    public String getAppointmentNumber() { return appointmentNumber; }
    public Patient getPatient() { return patient; }
    public Dentist getDentist() { return dentist; }
    public TreatmentType getTreatmentType() { return treatmentType; }
    public LocalDate getAppointmentDate() { return appointmentDate; }
    public LocalTime getAppointmentTime() { return appointmentTime; }
    public AppointmentStatus getStatus() { return status; }
    public void setStatus(AppointmentStatus status) { this.status = status; }
}
